# Python Basics

## Datatypes in Python 

Primitive Datatypes (Simplest Form holding a single value): int , float , string , bool <br/>
Non Primitive Datatypes (Complex Form can hold more than one value): List , Tuple , Set , Dictionary

In [1]:
print('Hello World!!')

Hello World!!


In [2]:
# for printing the dollar symbol twice 1 st way
print('$$')

$$


In [3]:
# second way 
print('$'*2)

$$


Any character wether it is numeric or string once enclosed withing the single quotes or double quotes will be considered as String

### Variables
A Variable is a named memory location which holds the data value of a particular datatype.<br/>
Variable in Python does not need initialization they gets assigned automatically.

In [4]:
var1 = 'Arsh'
var2 = 10
var3 = 10.12
var4 = True
print(f' Datatype of Var 1 {type(var1)} Datatype of Var 2 is {type(var2)} Datatype of Var3 is {type(var3)} Datatype of Var 4 is {type(var4)}')

 Datatype of Var 1 <class 'str'> Datatype of Var 2 is <class 'int'> Datatype of Var3 is <class 'float'> Datatype of Var 4 is <class 'bool'>


In [5]:
# Note : to get the input from the user use : input()

## Arithmatic Operations
### PEDMAS - Parenthesis Exponential Division Multiplication Addition Subtraction (Order of Operation)

In [6]:
a = 6
b = 5
print('Add : ',a+b)
print('Subtract : ',a-b)
print('Multiplication : ',a*b)
print('Division : ',a/b)
print('Modulous : ',a%b)
print('Power Function : ',a**b)

Add :  11
Subtract :  1
Multiplication :  30
Division :  1.2
Modulous :  1
Power Function :  7776


## String Operations
### We should look at the strings as the banner where multiple characters are linked together.
### The String data is immutable type which means it can not be modified.

In [7]:
# examples 
name = 'arsh'
is_technical = 'Yes'
print(name , is_technical)

arsh Yes


### Now when we want to include the words with single quotes for eg i'll didn't etc we will end up with a syntax error here.
### To prevent this we use the concept of escape sequence by using the forward slash \

In [8]:
# example of escape sequence 
print('I didn\'t knew this concept')

I didn't knew this concept


In [9]:
# similarly we have \n for the next line and \t for the tab space
print("This is line 1 \nThis is line 2")
print("Example of tab escape sequence\tis shown here")

This is line 1 
This is line 2
Example of tab escape sequence	is shown here


### String Concatination (+)

In [10]:
string1 = 'Hello'
string2 = 'World!'
string3 = string1+string2
print(string3)

HelloWorld!


In [11]:
# to find the length of the string : len()
print(f'{string3} length is {len(string3)}')

HelloWorld! length is 11


In [12]:
# accessing the first element of string
print(string3[0])

H


In [13]:
#accessing the last element of the string
print(string3[-1])

!


### Note : the indexing in string starts from 0 to length-1 and in python we have negative indexing also where -1 refers to last element -2 second last.. and so on

### Note : String are immutable i.e we can not change any character in the string

In [14]:
# example
#string3[0] = 'T' #  'str' object does not support item assignment

## String Slicing

#### Syntax : String[start:stop:stepsize]

In [15]:
# example 
test_case = '0 1 2 3 4 5 6 8 9 10 11 12 13 14 15'
print(type(test_case))

<class 'str'>


In [16]:
# slicing from index 0 to index 5
test_case[0:6]

'0 1 2 '

In [17]:
# to slice from beginning excluding the end
test_case[:-1]

'0 1 2 3 4 5 6 8 9 10 11 12 13 14 1'

In [18]:
# to slice from beginning to the end with step size of 2
test_case[::2]

'0123456891 11 31 5'

### Membership : We can check wether a specific character or string exists in the given string or not

In [19]:
statement1 = 'Hello this is Arsh Mishra , Nice to meet you!'
print('Hi' in statement1)

False


In [20]:
### Note it is case sensitive here
print('Hello' in statement1)

True


In [21]:
print('hello' in statement1)

False


### Let's see how to change the character case for a string or remove unwanted characters which are adjacent to the string

In [22]:
# .upper() is used to change it to uppercase
# .lower() is used to change it to lowercase
# stip() Removes extra spaces from both sides
# lstrip() Removed extra spaces from the left side
# rstrip() Removes extra spaces from the right side

In [23]:
statement2 = '   This is a sentence with Spacessssss      '

In [24]:
print(statement2)

   This is a sentence with Spacessssss      


In [25]:
print(statement2.upper())

   THIS IS A SENTENCE WITH SPACESSSSSS      


In [26]:
print(statement2.lower())

   this is a sentence with spacessssss      


In [27]:
print(statement2.lstrip())

This is a sentence with Spacessssss      


In [28]:
print(statement2.rstrip())

   This is a sentence with Spacessssss


In [29]:
print(statement2.strip())

This is a sentence with Spacessssss


In [30]:
# example
statement3 = "####12345678%%%%%"

In [31]:
print(statement3)

####12345678%%%%%


In [32]:
print(statement3.lstrip('#'))

12345678%%%%%


In [33]:
print(statement3.rstrip('%'))

####12345678


In [34]:
print(statement3.lstrip('#').rstrip('%'))

12345678


In [35]:
# split() : It Splits the String into substrings based on the separator chosen
statement4 = "Hello How are you"
print(statement4.split(' '))

['Hello', 'How', 'are', 'you']


In [36]:
# count() : It returns the count of the characters present in the string
print(statement4.count('H'))

2


In [37]:
print(statement4.count('o'))

3


## Python Data Structures

### Data Structures helps us in organizing the data in a well defined manner

### Lists 


Lists are the ordered sequence of the mixed datatypes , lists are mutable and allows duplicates. Lists are written as comma separated elements with square brackets

In [38]:
# empty list can be defined as 
list1 = []

In [39]:
type(list1)

list

In [40]:
list2 = ['Hi','Hello','Hola!']
print(list2)

['Hi', 'Hello', 'Hola!']


In [41]:
# list of mixed datatypes
list3 = ['Arsh',24,'Delhi',True]
print(list3)

['Arsh', 24, 'Delhi', True]


In [42]:
# Nested List : List withing a List
nested_list = [
    [1, 2, 3],       # Sublist 0
    [4, 5, 6, 7],    # Sublist 1
    [8, 9]           # Sublist 2
]

In [43]:
print(nested_list)

[[1, 2, 3], [4, 5, 6, 7], [8, 9]]


In [44]:
# Accessing elements using indexing
# Access 2 from Sublist 0
print("Element at nested_list[0][1]:", nested_list[0][1])
# Access 7 from Sublist 1
print("Element at nested_list[1][3]:", nested_list[1][3]) 
# Access 8 from Sublist 2
print("Element at nested_list[2][0]:", nested_list[2][0])  

Element at nested_list[0][1]: 2
Element at nested_list[1][3]: 7
Element at nested_list[2][0]: 8


In [45]:
# Slicing elements in a sublist
# Slice [5, 6] from Sublist 1
print(nested_list[1][1:3])
# Slice [1, 2] from Sublist 0
print(nested_list[0][:2])    

[5, 6]
[1, 2]


In [46]:
# Accessing each element
print(nested_list[0])
print(nested_list[1])
print(nested_list[2])

[1, 2, 3]
[4, 5, 6, 7]
[8, 9]


In [47]:
# List Concatination (+)
L1 = [1,2,3]
L2 = [4,5,6]
print(L1 + L2)

[1, 2, 3, 4, 5, 6]


In [48]:
# append() : it is used to add a single element or multiple elements to the list in the form of single element
# extend() : it is used to add multiple elements to the list  in the form of an iterable

In [49]:
list1 = [1, 2, 3]
list1.append([4, 5])  # Appending a list as a single element
print(list1)

[1, 2, 3, [4, 5]]


In [50]:
list2 = [1, 2, 3]
list2.extend([4, 5])  # Extending with elements of another list
print(list2)

[1, 2, 3, 4, 5]


In [51]:
list3 = ['A','B']
list3.append('C')       
list3.extend(['D', 'E']) 
print(list3)

['A', 'B', 'C', 'D', 'E']


In [52]:
# del keyword 
nums = [10,20,30,40,50,60,70,80,90,100]
print(nums)
del nums[0]
print("After using del nums[0] : ",nums)
del nums[1:3]
print("After using del nums[1:3] : ",nums)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
After using del nums[0] :  [20, 30, 40, 50, 60, 70, 80, 90, 100]
After using del nums[1:3] :  [20, 50, 60, 70, 80, 90, 100]


In [53]:
# pop keyword 
fruits = ["apple", "banana", "cherry", "dates", "pumpkin"]

# Default Behaviour is : To Remove and return the last element 
last_fruit = fruits.pop()
print("Removed last fruit:", last_fruit)
print("List after popping last element:", fruits)

# popping the element at index 1
second_fruit = fruits.pop(1)
print("Removed fruit at index 1:", second_fruit)
print("List after popping element at index 1:", fruits)


Removed last fruit: pumpkin
List after popping last element: ['apple', 'banana', 'cherry', 'dates']
Removed fruit at index 1: banana
List after popping element at index 1: ['apple', 'cherry', 'dates']


In [54]:
# remove keyword
# The remove method is used to remove the occurance of the first value in the list
numbers = [10, 20, 30, 20, 40, 20]
# Removes the first occurrence of 20
numbers.remove(20)  
print(numbers)

[10, 30, 20, 40, 20]


In [55]:
# sort() and sorted()

# .sort() : Sorts a list in-place (modifies the original list).
# sorted(): Returns a new sorted list (original list remains unchanged)

In [56]:
L = [32,24,1,3,8]
L.sort()
print('After using the .sort() : ',L)

After using the .sort() :  [1, 3, 8, 24, 32]


In [57]:
L2 = [32,24,1,3,8]
print("Sorting using .sorted() : ",sorted(L2))

Sorting using .sorted() :  [1, 3, 8, 24, 32]


### Note: L.sort() does not return anything , hence first we sorted the values first and then printed the list

In [58]:
# shadow copying
A =['orange','strawberry','mango']
B = A
print("List A : ",A)
print("List B : ",B)

List A :  ['orange', 'strawberry', 'mango']
List B :  ['orange', 'strawberry', 'mango']


In [59]:
A[0] = 'Pineapple'
print("List A : ",A)
print("List B : ",B)

List A :  ['Pineapple', 'strawberry', 'mango']
List B :  ['Pineapple', 'strawberry', 'mango']


In [60]:
# value changed in one list got updated in both , here both the list are rerencing to the single location

In [61]:
# example for preventing the shadow copying
C = ['Maruti','Honda','Skoda']
D = C[:]
print('List C : ',C)
print('List D : ',D)

List C :  ['Maruti', 'Honda', 'Skoda']
List D :  ['Maruti', 'Honda', 'Skoda']


In [62]:
C[0] = 'Mahindra'
print('List C : ',C)
print('List D : ',D)

List C :  ['Mahindra', 'Honda', 'Skoda']
List D :  ['Maruti', 'Honda', 'Skoda']


## Tuples 

### Tuples are similar to the lists in almost of their functionalities but there is one significant difference between both the data structures i.e. the lists are mutable whereas the tuples are immutable in nature

In [63]:
# Tuples are the ordered sequence of mixed elements or we can say datatypes ie the order in which the elements are inserted remains same
# tuples are written as comma separated elements which are enclosed within the circular brackets.

In [64]:
#  A tuple can be defined without parenthesis
tup1 = 1,2,3,4,5
print(tup1)
print(type(tup1))

(1, 2, 3, 4, 5)
<class 'tuple'>


In [65]:
# single value tuple
single_val_tup = 1, # Note : for defining the single value tuple we need to give , at the end
print(type(single_val_tup))

<class 'tuple'>


In [66]:
# Note :While defining the single Value Tuple If , is not included at the end then it will be the integer
eg = (1)
print(type(eg))

<class 'int'>


In [67]:
# concatination of tuples
tup1 = (1,2)
tup2 = (3,4)
print(tup1+tup2)

(1, 2, 3, 4)


In [68]:
# immortability of the tuples
t = ('USA',4,3,'DISCO',7.5)
#t[0] = 'Russia' # 'tuple' object does not support item assignment

In [69]:
# one way to make changes in the tuple is to first convert it into list make the changes and then again convert it back to tuple
ls = list(t)
ls[0] = 'Russia'
t = tuple(ls)
print(t)

('Russia', 4, 3, 'DISCO', 7.5)


In [70]:
# Nested Tuple : tuple within a tuple
t = (1,2,1.2,'party',(12,13,14))

In [71]:
# to access 14
print(t[4][-1])

14


### similarly we can do all the operations here as we do in the list only catch is the operation should make any changes in the existing tuple

## Sets

### Sets are the unordered collection i.e. it doesn't maintain the order in which the elements are inserted
### Sets are enclosed withing the curly braces {} and are written as comma separated .
### Sets doesn't allow duplicates

In [72]:
# example 
grades = ['A','B','C','C','D','D','A']
print(grades)

['A', 'B', 'C', 'C', 'D', 'D', 'A']


In [73]:
# creating set
set_of_grades = set(grades)
print(set_of_grades)

{'A', 'B', 'D', 'C'}


In [74]:
# set does not support indexing
#set_of_grades[0] # 'set' object is not subscriptable

In [75]:
# one way to define set 
set1 = {1,2,3,4,5}
# other way to define set
set2 = set([1,2,3,4])
print(set1)
print(set2)

{1, 2, 3, 4, 5}
{1, 2, 3, 4}


### Set Operations

In [76]:
A = {0,2,4,6,8}
B = {1,2,3,4,5,6,7}
print("Union of A , B :",A|B)
print("Union of A , B :",A.union(B))

Union of A , B : {0, 1, 2, 3, 4, 5, 6, 7, 8}
Union of A , B : {0, 1, 2, 3, 4, 5, 6, 7, 8}


In [77]:
print("Intersection of A , B :",A&B)
print("Intersection of A , B :",A.intersection(B))

Intersection of A , B : {2, 4, 6}
Intersection of A , B : {2, 4, 6}


In [78]:
print("A - B : ",A-B)
print("A - B : ",A.difference(B)) # elements occuring in A but not in B

A - B :  {0, 8}
A - B :  {0, 8}


In [79]:
# Symmetric Difference : Items either in A or B but not in the intersection i.e. Union - intersection
print(A^B)
print(A.symmetric_difference(B))

{0, 1, 3, 5, 7, 8}
{0, 1, 3, 5, 7, 8}


## Dictionaries

### Dictionary store elements as the key value pairs.
### The key is like an index it is always unique and immutable
### The Values are the objects which can be assesed using the keys
### The Values are mutable i.e. can be changed and also can be duplicates 

In [80]:
# syntax : {key1 : value1,key2 : value2......}

In [81]:
# example
currency = {'India':'Rupee','USA':'Dollar','France':'Euro'}
#Accessing the values
print(currency['India'])

Rupee


In [82]:
# inserting a new key value pair
currency['Japan'] = 'yen'

In [83]:
currency

{'India': 'Rupee', 'USA': 'Dollar', 'France': 'Euro', 'Japan': 'yen'}

In [84]:
#example of deleting
del currency['France']
print(currency)

{'India': 'Rupee', 'USA': 'Dollar', 'Japan': 'yen'}


In [85]:
removed_value = currency.pop('USA')
print("Removed currency:", removed_value)
print(currency)

Removed currency: Dollar
{'India': 'Rupee', 'Japan': 'yen'}


In [86]:
currency = {'India': 'Rupee', 'USA': 'Dollar', 'France': 'Euro'}

In [87]:
# extracting all values using .values()
values = currency.values()
print("Currency Values:", values)

Currency Values: dict_values(['Rupee', 'Dollar', 'Euro'])


In [88]:
# extracting all the keys
keys = currency.keys()
print("Keys:", keys)

Keys: dict_keys(['India', 'USA', 'France'])


In [89]:
# Updating dictionary using a new dictionary 
# D1.update(D2) is the syntax
new_currency = {'Japan': 'Yen', 'Germany': 'Euro'}
currency.update(new_currency)
print("Updated Dictionary after using update function :", currency)

Updated Dictionary after using update function : {'India': 'Rupee', 'USA': 'Dollar', 'France': 'Euro', 'Japan': 'Yen', 'Germany': 'Euro'}


In [90]:
# Accessing values using get function : get(key,"Not Found Message")
value = currency.get('USA', 'Not Found')
print("Value for USA:", value)

value = currency.get('Italy', 'Not Found')
print("Value for Italy:", value)

Value for USA: Dollar
Value for Italy: Not Found


### Sorted() Function

### sorted() function parametes explanation
### parameters are : iterable , key - (based on what needs to be sorted or a func to execute to decide the order, default is None) , reverse : if true then descending else ascending

In [91]:
# Sorting a list of numbers
numbers = [10, 3, 7, 1, 9]
sorted_numbers = sorted(numbers)
print(sorted_numbers)

[1, 3, 7, 9, 10]


In [92]:
# sorting based on the length of the word
words = ["apple", "banana", "cherry", "fig"]
sorted_words = sorted(words, key=len)
print(sorted_words)

['fig', 'apple', 'banana', 'cherry']


In [93]:
# sorting based on the second element of tuples
tuples = [(1, 3), (4, 1), (2, 5), (3, 2)]
sorted_tuples = sorted(tuples, key=lambda x: x[1]) #x[1] because in the lambda function a single tuple is getting passed
print(sorted_tuples)

[(4, 1), (3, 2), (1, 3), (2, 5)]


In [94]:
# sorting based on the last element of tuples
tuples2 = [(1, 3, 5), (4, 1, 4), (2, 5, 3), (3, 2, 9)]
sorted_tuples2 = sorted(tuples2, key=lambda x: x[-1])
print(sorted_tuples2)

[(2, 5, 3), (4, 1, 4), (1, 3, 5), (3, 2, 9)]


In [95]:
scores = {'Alice': 95, 'Bob': 85, 'Charlie': 90}
scores.items()

dict_items([('Alice', 95), ('Bob', 85), ('Charlie', 90)])

In [96]:
# lets sort using the values of the dictionary in reverse order
sorted_list = sorted(scores.items() , key=lambda x:x[1] , reverse=True)
print(sorted_list)

[('Alice', 95), ('Charlie', 90), ('Bob', 85)]


In [97]:
# sorting the list based on the squares of each element
numbers = [1, -3, 2, -4, 5]
sorted_numbers = sorted(numbers, key=lambda x: x**2)
print(sorted_numbers)

[1, 2, -3, -4, 5]


## Control Structures and Functions

### The most common control structures are if else , for and while loops , list and dictionary comprehensions

### Note : '=' is an assignment operator usefull for assigning the values to the variables
### '==' is the relational operator usefull for comparison checks

In [98]:
num = -5

if num >= 0:
    print("The number is positive.")
else:
    print("The number is negative.")

The number is negative.


In [99]:
# nested if else example
num = 10

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

The number is positive.


In [100]:
#Using or in If-else Statements
# in case of or if any one of the condition is true it results in true
num = -3

if num >= 0 or num == 0:
    print("The number is positive or zero.")
else:
    print("The number is negative.")

The number is negative.


In [101]:
#Using and in If-Else:
# in case of and both the conditions on the left , right side must be true for evaluating to true
num = 15

if num >= 10 and num <= 20:
    print("The number is between 10 and 20.")
else:
    print("The number is not between 10 and 20.")

The number is between 10 and 20.


In [102]:
# alsways evaluated from the left side 
if True or True:
    if False and True or False:
        print('A')
    elif False and False or True and True:
        print('B')
    else:
        print('C')

B


### Loops and iterations

### A for Loop is used when we know in advance how many times we want to iterate.

In [103]:
fruits = ['apple', 'banana', 'cherry']
for fruit in fruits:
    print(fruit)

apple
banana
cherry


In [104]:
for i in range(5):
    print(i , end=' ')

0 1 2 3 4 

### A while loop keeps repeating a task as long as a certain condition is true. It's useful when you don't know how many times the task will need to be done, and it depends on a condition that can change while the loop is running.

In [105]:
num = 0
while num < 5:
    print(num)
    num += 1

0
1
2
3
4


In [106]:
# iteraing over dictionary
students_data = {
    1:['Ram',24],
    2:['Shyam',24],
    3:['Ghanshyam',25]
}

In [107]:
students_data

{1: ['Ram', 24], 2: ['Shyam', 24], 3: ['Ghanshyam', 25]}

In [108]:
students_data.items()

dict_items([(1, ['Ram', 24]), (2, ['Shyam', 24]), (3, ['Ghanshyam', 25])])

In [109]:
# .items() func returned us the list of tuples having key and values
for key,value in students_data.items():
    print("Key is :",key," Value is : ",value)
    print("-----")

Key is : 1  Value is :  ['Ram', 24]
-----
Key is : 2  Value is :  ['Shyam', 24]
-----
Key is : 3  Value is :  ['Ghanshyam', 25]
-----


## Understanding range() function with variations

In [110]:
# range(stop) generating range from 0 to stop -1
for i in range(10):
    print(i,end='--')

0--1--2--3--4--5--6--7--8--9--

In [111]:
#range(start, stop) generating range from start to stop -1
for i in range(5,10):
    print(i,end='--')

5--6--7--8--9--

In [112]:
#range(start, stop, step) generating range from start to stop -1 with a step size
for i in range(0,10,2):
    print(i,end='--')

0--2--4--6--8--

In [113]:
# traversing in reverse order of range
for i in range(10,5,-1):
    print(i,end='--')

10--9--8--7--6--

## Comprehensions

### Comprehensions are syntactic constructs that enable sequences to be built from another sequences

In [114]:
#example
L1 = ['automobiles','Honda','Benz','Suzuki','BMW']
# goal is to create a list that contains the list of each word
# approach one
result = []
for word in L1:
    result.append(len(word))
print(result)    

[11, 5, 4, 6, 3]


In [115]:
res = [len(x) for x in L1]
print(res)

[11, 5, 4, 6, 3]


In [116]:
# given two list create a list by subtracting each element
L1 = [1,2,3,4,5]
L2 = [5,4,3,2,1]
l3 = [L1[i] - L2[i] for i in range(len(L1))]
print(l3)

[-4, -2, 0, 2, 4]


In [117]:
# Given List create a dictionary having key as word and value as length
L1 = ['automobiles','Honda','Benz','Suzuki','BMW']
dict1 = {x:len(x) for x in L1}
print(dict1)

{'automobiles': 11, 'Honda': 5, 'Benz': 4, 'Suzuki': 6, 'BMW': 3}


In [118]:
# create a dictionary that has first 10 even Natural nos as the key and their squares as the values
L2 = {i:i**2 for i in range(2,21) if i%2 == 0}
print(L2)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400}


### general syntax : [(the expression) for (the element) in (the iterable)]
### general syntax : [(the expression) for (the element) in (the iterable) if (condition)]

### List Comprehension with If Else

### general syntax : [(the expression) if condition else (the expression) for (the element) in (the iterable)]

In [119]:
# create a list of multiple of 6 for even nos btw 1 to 10 and multiple of 5 post that
l1 = [x*6 if (x>0 and x<=10) else x*5 for x in range(20)]
print(l1)

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [120]:
## list comprehension with nested loops
list1 = [1, 2, 3]
list2 = ['A', 'B', 'C']
list_product = [(x, y) for x in list1 for y in list2]
print(list_product)

[(1, 'A'), (1, 'B'), (1, 'C'), (2, 'A'), (2, 'B'), (2, 'C'), (3, 'A'), (3, 'B'), (3, 'C')]


### General Syntax : [(expression) for element in iterable (if condition) for element in iterable (if condition)...]

In [121]:
# Generate pairs of numbers where the sum is even
pairs = [(x,y) for x in range(10) if x%2==0 for y in range(5) if y%2 ==0]
print(pairs)

[(0, 0), (0, 2), (0, 4), (2, 0), (2, 2), (2, 4), (4, 0), (4, 2), (4, 4), (6, 0), (6, 2), (6, 4), (8, 0), (8, 2), (8, 4)]


## Functions

### Functions are the block of organized reusable code

### general syntax : def function_name(arguments): below this begins a function body


In [122]:
# to write a function that takes value as a parameter and returns an output
def factorial(n):
    if n == 1 :
        return 1
    else:
        return n * factorial(n-1)

In [123]:
factorial(5)

120

In [124]:
factorial(10)

3628800

In [125]:
# function arguments with default parameters
def func_with_params(name,age=25):
    print(name,'----',age)
    

In [126]:
func_with_params('Arsh')

Arsh ---- 25


In [127]:
func_with_params('Arsh',24)

Arsh ---- 24


In [128]:
#Note: Here Order Matters

In [129]:
## variable length argument func
def var_func(*args):
    print(args)

In [130]:
var_func('arsh','mishra',24)

('arsh', 'mishra', 24)


In [131]:
# variable length arguments returns a tuple

## Lambda Functions or Anonymous Functions

### Lambda functions are another way of defining functions to execute small functionalities occuring while implementing a complex functionality

In [132]:
## Syntax
# lambda input parameters : expression

In [133]:
## lambda func to check even or odd number
check_iseven = lambda x : 'even' if x%2==0 else 'odd'

In [134]:
check_iseven(2)

'even'

In [135]:
check_iseven(3)

'odd'

In [136]:
# return square using lambda function
square_it = lambda x: x**2

In [137]:
square_it(2)

4

In [138]:
square_it(3)

9

In [139]:
# calculate the max of three numbers
max_of_three = lambda x, y, z: x if (x > y and x > z) else (y if (y > z) else z)

In [140]:
#  in the first condition we are checking if x is greater than y and x is greater than z (if false -> it means x is less than y or x is less than z)
# so comparing the variables y and z to check the maximum number

In [141]:
max_of_three(1,2,3)

3

In [142]:
max_of_three(6,5,7)

7

## Map Function

 Map is a function that works like the list comprehensions and for loops , it is used when we need to implement the func on multiple elements at the same time

In [143]:
# syntax : map(function,iterable,*iterables)
# function - > the function that we want to apply on the iterable
# iterable - > the iterable on which the function will be applied
# *iterables - > (optional) list of iterables Note : number of iterables will be same as the number of arguments 

In [144]:
# example 1
# defining iterable
iterable1 = [10,20,30,40,50]
# defining function
def square_number(x):
    return x**2
output_list1 = map(square_number,iterable1) 
print(list(output_list1))

[100, 400, 900, 1600, 2500]


In [145]:
# example 2
iter1 = [40,30,20,10]
iter2 = [10,20,30,40]
def calculate_sum(x,y):
    return x+y
output = list(map(calculate_sum,iter1,iter2)) 
print(output)

[50, 50, 50, 50]


## Filter Operation

Filter Operation is similar to map , the only distuinguishing feature is that it requires the function to look for the conditions and return only those that satisfies the condition

i.e. it is used to filter elements from an iterable based on a condition. It returns a new iterable (a filter object) containing only the elements for which the provided function returns True.

In [146]:
# Syntax : filter(function,iterable object)

In [147]:
# filter function to return the multiple of 3
my_list = [9,8,7,6,5,4,3,2,1]
print(list(filter(lambda x:x%3==0,my_list)))

[9, 6, 3]


In [148]:
# write a python program to count the students above age 18 
students_data = {
    1 : ['sam',15],
    2 : ['Ram',19],
    3 : ['Yon',19]
}

In [149]:
f = lambda x : x[1]>18

In [150]:
print(list(filter(f,students_data.values())))

[['Ram', 19], ['Yon', 19]]


In [151]:
# for count use len function
print(len(list(filter(f,students_data.values()))))

2


## Reduce Functions

Reduce is an operation that breaks down the entire process into the pair wise operations and uses the result from each operation with the successive elements

In [152]:
# Syntax : reduce(function,iterable object)

In [153]:
# The iterable object can be a string , tuple , list etc , Reduce function produces only one output

In [154]:
from functools import reduce

In [155]:
# reduce to produce the product of the elements of the iterable
iter = [1,2,3,4,5,6,7,8,9]
print(reduce(lambda x,y:x*y,iter))

362880


In [156]:
# return the sum of all the elements in the list
ls = [1,4,5,6,7,9,3,2,11]
print(reduce(lambda x,y:x+y,ls))

48


# Numpy

### Numpy stands for Numerical Python , it's a library used for extensive mathematical computation .

### Numpy arrays are faster and are more convenient as compared to the traditional lists when it comes to computing

### NumPy arrays store elements of the same data type, which means the memory layout is contiguous and efficient.
### Python lists can store elements of different data types, so each element is a separate object with its own metadata, leading to additional overhead.

### NumPy arrays use contiguous blocks of memory, which allows the CPU to efficiently load data into its cache and perform operations quickly.
### Python lists store references to objects that are scattered in memory, resulting in more time-consuming memory lookups.

In [157]:
import numpy as np

In [158]:
# creating an array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [159]:
# creating array from tuple
my_tup = (1,2,3,4,)
type(my_tup)

tuple

In [160]:
my_arr = np.array(my_tup)
print("Array : ",my_arr, "Dtype  : ",type(my_arr) )
my_ls = [1,2,3,4]
print("List : ",my_ls, "Dtype : ",type(my_ls))

Array :  [1 2 3 4] Dtype  :  <class 'numpy.ndarray'>
List :  [1, 2, 3, 4] Dtype :  <class 'list'>


In [161]:
# checking the numpy version .__version__
print("version of the numpy is : ",np.__version__)

version of the numpy is :  1.26.2


### Dimensions of the array 0D , 1D , 2D , 3D

In [162]:
# for checking the dimensions of the array we use .ndim


In [163]:
# 0D Array aka Scalars
zero_d_arr = np.array(10)
print(zero_d_arr)
print(zero_d_arr.ndim)

10
0


In [164]:
# 1D Array : An array that have 0D elements (scalars) as its elements
one_d_arr = np.array([1,2,3,4,5])
print(one_d_arr)
print(one_d_arr.ndim)

[1 2 3 4 5]
1


In [165]:
# 2D Array : An array that have 1D array as its elements
two_d_arr = np.array([[1,2,3],[4,5,6]])
print(two_d_arr)
print(two_d_arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [166]:
# Three Dimension : An array that has 2D array as its elements 
three_d_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_d_arr)
print(three_d_arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [167]:
# other way to check the dimensions is to see the number of ] at the end of the array eg in the above case it's 3 ] so 3D

### Numpy array indexing

In [168]:
arr = np.array([1,2,3,4])
print("First element : ",arr[0])
print("Last element : ",arr[-1])
print("Second element : ",arr[1])

First element :  1
Last element :  4
Second element :  2


In [169]:
# accessing the 2D Elements
arr = np.array([[1,2,3],[4,5,6]])
print("Array Entered : ",arr)
print("Dimension : ",arr.ndim)

Array Entered :  [[1 2 3]
 [4 5 6]]
Dimension :  2


In [170]:
# Syntax   :  array[row index,col index]
# example : to access 4
# below are the two ways
print(arr[1,0])
print(arr[1][0])

4
4


In [171]:
# printing 6
print(arr[1][-1])

6


In [172]:
# Three Dimension : An array that has 2D array as its elements 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [173]:
# printing 12
print(arr[1])

[[ 7  8  9]
 [10 11 12]]


In [174]:
print(arr[1][1])

[10 11 12]


In [175]:
print(arr[1][1][-1])
print(arr[1,1,-1])

12
12


### Slicing arrays 
Slicing in python means taking elements from one index to another index. 

Syntax  : [start index:stop index:stepsize] Note : default value of step size is 1 <br/>
If we dont pass start it is considered as 0.<br/>
If we dont pass end it is considered as the length of the array.
<br/>
<br/>
Note : The result consider includes the starting index but exclude the ending index , it only considers (last index -1) .

In [176]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print("Sliced elements from 2 to 7 : ",arr[1:])
print("Sliced elements from beginning to 5 : ",arr[:5])
print("Slicing with a step size of 2 : ",arr[::2])

[1 2 3 4 5 6 7]
Sliced elements from 2 to 7 :  [2 3 4 5 6 7]
Sliced elements from beginning to 5 :  [1 2 3 4 5]
Slicing with a step size of 2 :  [1 3 5 7]


In [177]:
# Negative Slicing 
print(arr[-4:-1])
print(arr[-6::2])

[4 5 6]
[2 4 6]


In [178]:
# slicing in 2D arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr[1,1:])

2
[5 6]


In [179]:
# syntax is start:stop:stepsize 

### Converting dataype on the existing arrays 
The best way to convert the datatype of the existing array is to make the copy of the array with astype() function , this function creates a copy of the array and allows us to specify the datatype as the parameter .

In [180]:
arr = np.array([1.2,2.3,3.4])
new_arr = arr.astype('i')
print(arr)
print(new_arr)

[1.2 2.3 3.4]
[1 2 3]


In [181]:
print(int(1.9))

1


In [182]:
# while making the conversion from float to int all the values after the decimal point will be removed.

### Numpy Copy Vs View 

The main difference between the two is that copy creates a totally new array so that the new array and the original arrays are seperate , but in case of view , the view is just the image of the original array , so any change in the original array or the view will reflect in the other one , whereas in case of copy any change made in the original array wont have any impact on the copied array.

In [183]:
# example of copy()
original_arr = np.array([1,2,3])
copied_arr = original_arr.copy()
original_arr[0] = 10
print("Original : ",original_arr)
print("Copied : ",copied_arr)

Original :  [10  2  3]
Copied :  [1 2 3]


In [184]:
# example of view()
original_arr = np.array([1,2,3])
view_arr = original_arr.view()
original_arr[0] = 10
print("Original : ",original_arr)
print("View : ",view_arr)

Original :  [10  2  3]
View :  [10  2  3]


### Numpy array shape 

It tells the number of elements in each dimension , for this we use .shape() function

In [185]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print('----')
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)

(3,)
----
(2, 3)


### Numpy array reshaping 

It is usefull when we want to change the shape of the existing array to the new array , but the number of elements before and after change must be same.

In [186]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print('------')
arr2 = arr.reshape(3,2)
print(arr2)
print('------')
arr3 = arr.reshape(2,3)
print(arr3)

[1 2 3 4 5 6]
------
[[1 2]
 [3 4]
 [5 6]]
------
[[1 2 3]
 [4 5 6]]


### Array Flattening

In [187]:
print(arr3)

[[1 2 3]
 [4 5 6]]


In [188]:
flattened_array = arr3.reshape(-1)
print(flattened_array)

[1 2 3 4 5 6]


### Numpy array itertion 

It means going through each element one by one.

In [189]:
arr = np.array([1,2,3,4,5,6,7,8,9])
for ele in arr:
    print(ele , end = '--')

1--2--3--4--5--6--7--8--9--

In [190]:
arr = np.array([[1,2,3],[4,5,6]])
for row in arr:
    print(row)
    print('---------')
    for col in row:
        print(col )

[1 2 3]
---------
1
2
3
[4 5 6]
---------
4
5
6


### Numpy searching arrays

We can search an array for a certain value and return the index that get's a match. For this we use .where() function 

In [191]:
arr = np.array([1,2,3,4,5,4,4,2,1])
print(np.where(arr==4))
print(np.where(arr==2))

(array([3, 5, 6], dtype=int64),)
(array([1, 7], dtype=int64),)


### Numpy vs List

In [192]:
heights = [74 ,75 , 72,72,71]

#Now if we want to multiply heights by 2.54 we will get an error
# heights * 2.54  --- >  can't multiply sequence by non-int of type 'float'
# so for doing this we need to use for loop or the list comprehensions
formatted_heights = [2.53*x for x in heights]
print(formatted_heights)

[187.22, 189.74999999999997, 182.16, 182.16, 179.63]


In [193]:
# Better soln is to use the numpy arrays for this because numpy has the capability to perform element wise operations

heights_arr = np.array(heights)
print(heights_arr * 2.53)

[187.22 189.75 182.16 182.16 179.63]


In [194]:
# to check the type of the heights_arr
type(heights_arr)

numpy.ndarray

In [195]:
# Performing operations on numpy arrays

arr1 = np.array([1,2,3,4,5])
print("Sum of elements : ",sum(arr1))
arr2 = np.array([5,4,3,2,1])
print("add operation : ",arr1+arr2)
print("sub operation : ",arr1-arr2)
print("division operation : ",arr1/arr2)
print("multiplication operation : ",arr1*arr2)

Sum of elements :  15
add operation :  [6 6 6 6 6]
sub operation :  [-4 -2  0  2  4]
division operation :  [0.2 0.5 1.  2.  5. ]
multiplication operation :  [5 8 9 8 5]


In [196]:
# note : operations are happening between the elements i.e. these are element wise operations

<h2 style = "color : Brown"> Case Study - Cricket Tournament </h2>

A panel wants to select players for an upcoming league match based on their fitness. Players from all significant cricket clubs have participated in a practice match, and their data is collected. Let us now explore NumPy features using the player's data.</font>

<h4 style = "color : Sky blue"> Example - 1</h4>  

#### Heights of the players is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it ?

In [197]:
# Define list
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

In [198]:
#converting to numpy arrays
heights_arr = np.array(heights)

In [199]:
# for counting the number of participants
len(heights_arr)

1015

In [200]:
heights_arr.shape

(1015,)

In [201]:
heights_arr.size

1015

In [202]:
# converting the heights from inches to meters
heights_mtrs = heights_arr * 0.0254

In [203]:
print(heights_mtrs[:10])

[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034]


<h4 style = "color : Sky blue"> Example - 4</h4>

#### A list of weights (in lbs) of the players is provided. Convert it to kg and calculate BMI

In [204]:
weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [205]:
#converting the list to arr
weights_arr = np.array(weights_lb)

In [206]:
type(weights_lb)

list

In [207]:
type(weights_arr)

numpy.ndarray

In [208]:
# to convert from lbs to kg 
weights_kg = weights_arr*0.453

### Calculating BMI 
BMI = weight(kg) / height(m)**2


In [209]:
BMI_arr = weights_kg/heights_mtrs **2 # PEDMAS

In [210]:
print(BMI_arr[:10])

[23.08021417 27.56803359 28.44363328 28.44363328 24.77096341 25.95644763
 30.82328156 27.85762366 28.08119363 25.07186129]


In [211]:
print("BMI Records for first 5 members : ",BMI_arr[0:5])
print("BMI Records for the last 5 members : ",BMI_arr[-5:])

BMI Records for first 5 members :  [23.08021417 27.56803359 28.44363328 28.44363328 24.77096341]
BMI Records for the last 5 members :  [25.0344843  23.08021417 25.58951785 23.7171141  25.69328652]


In [212]:
# Conditional Subsetting

# Count the Number of participants that have BMI > 21
print(BMI_arr > 21) # returns a list of true / false and then we are using that as an index
print("Members who have BMI > 21 : ",len(BMI_arr[BMI_arr>21]))

[ True  True  True ...  True  True  True]
Members who have BMI > 21 :  1004


In [213]:
print("Maximum BMI : ",max(BMI_arr),"  ----------  ",np.max(BMI_arr)) 
print("Minimum BMI : ",min(BMI_arr),"  ----------  ",np.min(BMI_arr)) 
print("Average BMI : ",BMI_arr.mean(),"  ----------  ",np.mean(BMI_arr)) 

Maximum BMI :  35.21592691333531   ----------   35.21592691333531
Minimum BMI :  19.472998945997894   ----------   19.472998945997894
Average BMI :  26.022837884005778   ----------   26.022837884005778


In [214]:
# multiple condition
print("People having BMI > 25 and < 30 :",len(BMI_arr[(BMI_arr > 25) & (BMI_arr < 30)])) # conditions are written in ()

People having BMI > 25 and < 30 : 636


## Multidimensional arrays
Multidimesnional arrays are basically the arrays within an array , so a 2d array is an array with each elements as the 1 d array

<h2 style = "color : Brown"> Case Study - Cricket Tournament </h2>

<h4 style = "color : Sky blue"> Example - 1</h4>  

##### Players list contain the height(inches) and weight(lbs) data for all the players

In [215]:
# list of height and weight of the players.
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180), (70, 185), (73, 189), (75, 185), (78, 219), (79, 230), (76, 205), (74, 230), (76, 195), (72, 180), (71, 192), (75, 225), (77, 203), (74, 195), (73, 182), (74, 188), (78, 200), (73, 180), (75, 200), (73, 200), (75, 245), (75, 240), (74, 215), (69, 185), (71, 175), (74, 199), (73, 200), (73, 215), (76, 200), (74, 205), (74, 206), (70, 186), (72, 188), (77, 220), (74, 210), (70, 195), (73, 200), (75, 200), (76, 212), (76, 224), (78, 210), (74, 205), (74, 220), (76, 195), (77, 200), (81, 260), (78, 228), (75, 270), (77, 200), (75, 210), (76, 190), (74, 220), (72, 180), (72, 205), (75, 210), (73, 220), (73, 211), (73, 200), (70, 180), (70, 190), (70, 170), (76, 230), (68, 155), (71, 185), (72, 185), (75, 200), (75, 225), (75, 225), (75, 220), (68, 160), (74, 205), (78, 235), (71, 250), (73, 210), (76, 190), (74, 160), (74, 200), (79, 205), (75, 222), (73, 195), (76, 205), (74, 220), (74, 220), (73, 170), (72, 185), (74, 195), (73, 220), (74, 230), (72, 180), (73, 220), (69, 180), (72, 180), (73, 170), (75, 210), (75, 215), (73, 200), (72, 213), (72, 180), (76, 192), (74, 235), (72, 185), (77, 235), (74, 210), (77, 222), (75, 210), (76, 230), (80, 220), (74, 180), (74, 190), (75, 200), (78, 210), (73, 194), (73, 180), (74, 190), (75, 240), (76, 200), (71, 198), (73, 200), (74, 195), (76, 210), (76, 220), (74, 190), (73, 210), (74, 225), (70, 180), (72, 185), (73, 170), (73, 185), (73, 185), (73, 180), (71, 178), (74, 175), (74, 200), (72, 204), (74, 211), (71, 190), (74, 210), (73, 190), (75, 190), (75, 185), (79, 290), (73, 175), (75, 185), (76, 200), (74, 220), (76, 170), (78, 220), (74, 190), (76, 220), (72, 205), (74, 200), (76, 250), (74, 225), (75, 215), (78, 210), (75, 215), (72, 195), (74, 200), (72, 194), (74, 220), (70, 180), (71, 180), (70, 170), (75, 195), (71, 180), (71, 170), (73, 206), (72, 205), (71, 200), (73, 225), (72, 201), (75, 225), (74, 233), (74, 180), (75, 225), (73, 180), (77, 220), (73, 180), (76, 237), (75, 215), (74, 190), (76, 235), (75, 190), (73, 180), (71, 165), (76, 195), (75, 200), (72, 190), (71, 190), (77, 185), (73, 185), (74, 205), (71, 190), (72, 205), (74, 206), (75, 220), (73, 208), (72, 170), (75, 195), (75, 210), (74, 190), (72, 211), (74, 230), (71, 170), (70, 185), (74, 185), (77, 241), (77, 225), (75, 210), (75, 175), (78, 230), (75, 200), (76, 215), (73, 198), (75, 226), (75, 278), (79, 215), (77, 230), (76, 240), (71, 184), (75, 219), (74, 170), (69, 218), (71, 190), (76, 225), (72, 220), (72, 176), (70, 190), (72, 197), (73, 204), (71, 167), (72, 180), (71, 195), (73, 220), (72, 215), (73, 185), (74, 190), (74, 205), (72, 205), (75, 200), (74, 210), (74, 215), (77, 200), (75, 205), (73, 211), (72, 190), (71, 208), (74, 200), (77, 210), (75, 232), (75, 230), (75, 210), (78, 220), (78, 210), (74, 202), (76, 212), (78, 225), (76, 170), (70, 190), (72, 200), (80, 237), (74, 220), (74, 170), (71, 193), (70, 190), (72, 150), (71, 220), (74, 200), (71, 190), (72, 185), (71, 185), (74, 200), (69, 172), (76, 220), (75, 225), (75, 190), (76, 195), (73, 219), (76, 190), (73, 197), (77, 200), (73, 195), (72, 210), (72, 177), (77, 220), (77, 235), (71, 180), (74, 195), (74, 195), (73, 190), (78, 230), (75, 190), (73, 200), (70, 190), (74, 190), (72, 200), (73, 200), (73, 184), (75, 200), (75, 180), (74, 219), (76, 187), (73, 200), (74, 220), (75, 205), (75, 190), (72, 170), (73, 160), (73, 215), (72, 175), (74, 205), (78, 200), (76, 214), (73, 200), (74, 190), (75, 180), (70, 205), (75, 220), (71, 190), (72, 215), (78, 235), (75, 191), (73, 200), (73, 181), (71, 200), (75, 210), (77, 240), (72, 185), (69, 165), (73, 190), (74, 185), (72, 175), (70, 155), (75, 210), (70, 170), (72, 175), (72, 220), (74, 210), (73, 205), (74, 200), (76, 205), (75, 195), (80, 240), (72, 150), (75, 200), (73, 215), (74, 202), (74, 200), (73, 190), (75, 205), (75, 190), (71, 160), (73, 215), (75, 185), (74, 200), (74, 190), (72, 210), (74, 185), (74, 220), (74, 190), (73, 202), (76, 205), (75, 220), (72, 175), (73, 160), (73, 190), (73, 200), (72, 229), (72, 206), (72, 220), (72, 180), (71, 195), (75, 175), (75, 188), (74, 230), (73, 190), (75, 200), (79, 190), (74, 219), (76, 235), (73, 180), (74, 180), (74, 180), (72, 200), (74, 234), (74, 185), (75, 220), (78, 223), (74, 200), (74, 210), (74, 200), (77, 210), (70, 190), (73, 177), (74, 227), (73, 180), (71, 195), (75, 199), (71, 175), (72, 185), (77, 240), (74, 210), (70, 180), (77, 194), (73, 225), (72, 180), (76, 205), (71, 193), (76, 230), (78, 230), (75, 220), (73, 200), (78, 249), (74, 190), (79, 208), (75, 245), (76, 250), (72, 160), (75, 192), (75, 220), (70, 170), (72, 197), (70, 155), (74, 190), (71, 200), (76, 220), (73, 210), (76, 228), (71, 190), (69, 160), (72, 184), (72, 180), (69, 180), (73, 200), (69, 176), (73, 160), (74, 222), (74, 211), (72, 195), (71, 200), (72, 175), (72, 206), (76, 240), (76, 185), (76, 260), (74, 185), (76, 221), (75, 205), (71, 200), (72, 170), (71, 201), (73, 205), (75, 185), (76, 205), (75, 245), (71, 220), (75, 210), (74, 220), (72, 185), (73, 175), (73, 170), (73, 180), (73, 200), (76, 210), (72, 175), (76, 220), (73, 206), (73, 180), (73, 210), (75, 195), (75, 200), (77, 200), (73, 164), (72, 180), (75, 220), (70, 195), (74, 205), (72, 170), (80, 240), (71, 210), (71, 195), (74, 200), (74, 205), (73, 192), (75, 190), (76, 170), (73, 240), (77, 200), (72, 205), (73, 175), (77, 250), (76, 220), (71, 224), (75, 210), (73, 195), (74, 180), (77, 245), (71, 175), (72, 180), (73, 215), (69, 175), (73, 180), (70, 195), (74, 230), (76, 230), (73, 205), (73, 215), (75, 195), (73, 180), (79, 205), (74, 180), (73, 190), (74, 180), (77, 190), (75, 190), (74, 220), (73, 210), (77, 255), (73, 190), (77, 230), (74, 200), (74, 205), (73, 210), (77, 225), (74, 215), (77, 220), (75, 205), (77, 200), (75, 220), (71, 197), (74, 225), (70, 187), (79, 245), (72, 185), (72, 185), (70, 175), (74, 200), (74, 180), (72, 188), (73, 225), (72, 200), (74, 210), (74, 245), (76, 213), (82, 231), (74, 165), (74, 228), (70, 210), (73, 250), (73, 191), (74, 190), (77, 200), (72, 215), (76, 254), (73, 232), (73, 180), (72, 215), (74, 220), (74, 180), (71, 200), (72, 170), (75, 195), (74, 210), (74, 200), (77, 220), (70, 165), (71, 180), (73, 200), (76, 200), (71, 170), (75, 224), (74, 220), (72, 180), (76, 198), (79, 240), (76, 239), (73, 185), (76, 210), (78, 220), (75, 200), (76, 195), (72, 220), (72, 230), (73, 170), (73, 220), (75, 230), (71, 165), (76, 205), (70, 192), (75, 210), (74, 205), (75, 200), (73, 210), (71, 185), (71, 195), (72, 202), (73, 205), (73, 195), (72, 180), (69, 200), (73, 185), (78, 240), (71, 185), (73, 220), (75, 205), (76, 205), (70, 180), (74, 201), (77, 190), (75, 208), (79, 240), (72, 180), (77, 230), (73, 195), (75, 215), (75, 190), (75, 195), (73, 215), (73, 215), (76, 220), (77, 220), (75, 230), (70, 195), (71, 190), (71, 195), (75, 209), (74, 204), (69, 170), (70, 185), (75, 205), (72, 175), (75, 210), (73, 190), (72, 180), (72, 180), (72, 160), (76, 235), (75, 200), (74, 210), (69, 180), (73, 190), (72, 197), (72, 203), (75, 205), (77, 170), (76, 200), (80, 250), (77, 200), (76, 220), (79, 200), (71, 190), (75, 170), (73, 190), (76, 220), (77, 215), (73, 206), (76, 215), (70, 185), (75, 235), (73, 188), (75, 230), (70, 195), (69, 168), (71, 190), (72, 160), (72, 200), (73, 200), (70, 189), (70, 180), (73, 190), (76, 200), (75, 220), (72, 187), (73, 240), (79, 190), (71, 180), (72, 185), (74, 210), (74, 220), (74, 219), (72, 190), (76, 193), (76, 175), (72, 180), (72, 215), (71, 210), (72, 200), (72, 190), (70, 185), (77, 220), (74, 170), (72, 195), (76, 205), (71, 195), (76, 210), (71, 190), (73, 190), (70, 180), (73, 220), (73, 190), (72, 186), (71, 185), (71, 190), (71, 180), (72, 190), (72, 170), (74, 210), (74, 240), (74, 220), (71, 180), (72, 210), (75, 210), (72, 195), (71, 160), (72, 180), (72, 205), (72, 200), (72, 185), (74, 245), (74, 190), (77, 210), (75, 200), (73, 200), (75, 222), (73, 215), (76, 240), (72, 170), (77, 220), (75, 156), (72, 190), (71, 202), (71, 221), (75, 200), (72, 190), (73, 210), (73, 190), (71, 200), (70, 165), (75, 190), (71, 185), (76, 230), (73, 208), (68, 209), (71, 175), (72, 180), (74, 200), (77, 205), (72, 200), (76, 250), (78, 210), (81, 230), (72, 244), (73, 202), (76, 240), (72, 200), (72, 215), (74, 177), (76, 210), (73, 170), (76, 215), (75, 217), (70, 198), (71, 200), (74, 220), (72, 170), (73, 200), (76, 230), (76, 231), (73, 183), (71, 192), (68, 167), (71, 190), (71, 180), (74, 180), (77, 215), (69, 160), (72, 205), (76, 223), (75, 175), (76, 170), (75, 190), (76, 240), (72, 175), (74, 230), (76, 223), (74, 196), (72, 167), (75, 195), (78, 190), (77, 250), (70, 190), (72, 190), (79, 190), (74, 170), (71, 160), (68, 150), (77, 225), (75, 220), (71, 209), (72, 210), (70, 176), (72, 260), (72, 195), (73, 190), (72, 184), (74, 180), (72, 195), (72, 195), (75, 219), (72, 225), (73, 212), (74, 202), (72, 185), (78, 200), (75, 209), (72, 200), (74, 195), (75, 228), (75, 210), (76, 190), (74, 212), (74, 190), (73, 218), (74, 220), (71, 190), (74, 235), (75, 210), (76, 200), (74, 188), (76, 210), (76, 235), (73, 188), (75, 215), (75, 216), (74, 220), (68, 180), (72, 185), (75, 200), (71, 210), (70, 220), (72, 185), (73, 231), (72, 210), (75, 195), (74, 200), (70, 205), (76, 200), (71, 190), (82, 250), (72, 185), (73, 180), (74, 170), (71, 180), (75, 208), (77, 235), (72, 215), (74, 244), (72, 220), (73, 185), (78, 230), (77, 190), (73, 200), (73, 180), (73, 190), (73, 196), (73, 180), (76, 230), (75, 224), (70, 160), (73, 178), (72, 205), (73, 185), (75, 210), (74, 180), (73, 190), (73, 200), (76, 257), (73, 190), (75, 220), (70, 165), (77, 205), (72, 200), (77, 208), (74, 185), (75, 215), (75, 170), (75, 235), (75, 210), (72, 170), (74, 180), (71, 170), (76, 190), (71, 150), (75, 230), (76, 203), (83, 260), (75, 246), (74, 186), (76, 210), (72, 198), (72, 210), (75, 215), (75, 180), (72, 200), (77, 245), (73, 200), (72, 192), (70, 192), (74, 200), (72, 192), (74, 205), (72, 190), (71, 186), (70, 170), (71, 197), (76, 219), (74, 200), (76, 220), (74, 207), (74, 225), (74, 207), (75, 212), (75, 225), (71, 170), (71, 190), (74, 210), (77, 230), (71, 210), (74, 200), (75, 238), (77, 234), (76, 222), (74, 200), (76, 190), (72, 170), (71, 220), (72, 223), (75, 210), (73, 215), (68, 196), (72, 175), (69, 175), (73, 189), (73, 205), (75, 210), (70, 180), (70, 180), (74, 197), (75, 220), (74, 228), (74, 190), (73, 204), (74, 165), (75, 216), (77, 220), (73, 208), (74, 210), (76, 215), (74, 195), (75, 200), (73, 215), (76, 229), (78, 240), (75, 207), (73, 205), (77, 208), (74, 185), (72, 190), (74, 170), (72, 208), (71, 225), (73, 190), (75, 225), (73, 185), (67, 180), (67, 165), (76, 240), (74, 220), (73, 212), (70, 163), (75, 215), (70, 175), (72, 205), (77, 210), (79, 205), (78, 208), (74, 215), (75, 180), (75, 200), (78, 230), (76, 211), (75, 230), (69, 190), (75, 220), (72, 180), (75, 205), (73, 190), (74, 180), (75, 205), (75, 190), (73, 195)]

In [216]:
# converting to array
players_arr = np.array(players)

In [217]:
players_arr.ndim

2

In [218]:
players_arr.shape

(1015, 2)

In [219]:
# to convert the height to meters and weights to kgs
players_converted = players_arr * [0.0254,0.453]

In [220]:
# fetching the height of the 125th player
print("Data for 125th player :",players_converted[124])
print("Height of 125th player :",players_converted[124][0])
print("Weight of the 125th Player : ",players_converted[124][1])

Data for 125th player : [ 1.9812 95.13  ]
Height of 125th player : 1.9811999999999999
Weight of the 125th Player :  95.13000000000001


### Conditional Subsetting

In [221]:
# info of players whose heights > 1.8m
print(players_converted[:,0]>1.8)
print("Tall players Count : ",len(players_converted[players_converted[:,0]>1.8]))

[ True  True  True ...  True  True  True]
Tall players Count :  936


### Skills Array - holds the player key skills.

In [222]:
skills = np.array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper', 'Keeper', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman'])
skills

array(['Keeper', 'Batsman', 'Bowler', ..., 'Batsman', 'Bowler',
       'Keeper-Batsman'], dtype='<U14')

In [223]:
# converting skills to array 
skills_arr = np.array(skills)

In [224]:
# fetch the heights of the batsman
skills_arr  == 'Batsman'

array([False,  True, False, ...,  True, False, False])

In [225]:
players_converted[skills_arr=='Batsman'][:,0]

array([1.8796, 1.8542, 1.7526, 1.8034, 1.9304, 1.8542, 1.8542, 1.778 ,
       2.0066, 1.8288, 1.8034, 1.905 , 1.9558, 1.8542, 1.905 , 1.8796,
       1.8034, 1.8542, 1.8796, 1.9304, 1.905 , 1.9304, 1.8288, 1.905 ,
       1.8542, 1.778 , 1.778 , 1.8034, 1.8288, 1.905 , 1.9812, 1.8034,
       1.8542, 1.8542, 1.9304, 1.8796, 1.8542, 1.8288, 1.8542, 1.8288,
       1.8542, 1.8288, 1.905 , 1.905 , 1.8288, 1.8288, 1.9558, 1.9558,
       1.905 , 1.9304, 2.032 , 1.905 , 1.8542, 1.8796, 1.905 , 1.8034,
       1.9304, 1.8796, 1.8542, 1.8542, 1.8034, 1.8542, 1.8542, 1.8288,
       1.905 , 1.778 , 1.8034, 1.8288, 1.905 , 1.8542, 1.9304, 1.905 ,
       1.9304, 1.8288, 1.8542, 1.905 , 1.8796, 1.8034, 1.9558, 1.9812,
       1.905 , 1.905 , 1.9304, 1.8288, 1.8288, 1.8542, 1.8796, 1.8796,
       1.905 , 1.8542, 1.8796, 1.9558, 1.9812, 1.9812, 1.8796, 1.9812,
       1.8796, 1.8288, 1.9304, 1.8542, 1.8542, 1.9558, 1.9558, 1.8034,
       1.9812, 1.778 , 1.8796, 1.8288, 1.8542, 1.905 , 1.8796, 1.8542,
      

In [226]:
print("Count of batsman in the team : ",len(players_converted[skills_arr=='Batsman'][:,0]))

Count of batsman in the team :  323


## Creating Numpy Arrays Shortcuts

The following ways are commonly used when we know the size of the array before hand <br/>
np.ones() : it is used to create the array of ones 
<br/>
np.zeros() : it is used to create the array of zeros
<br/>
np.random.randint() : it is used to create the random array of integers withing a range
<br/>
np.random.random() : it is used to create a random array of integers.
<br/>
np.arange() : it is used to create an array with increments of fixed length size.
<br/>
np.linspace() : it is used to create an array of equally spaced elements of fixed length


In [227]:
# creating a one dim array of ones of length 5
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [228]:
# by default it creates an array of float type

arr = np.ones(5,dtype=int)
print(arr)

[1 1 1 1 1]


In [229]:
# create a 5x3 array of ones
arr_2d = np.ones((5,3),dtype=int)
print(arr_2d)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [230]:
# creating an array of zeros
arr = np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


In [231]:
arr_2d = np.zeros((5,3),dtype = int)
print(arr_2d)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [232]:
# using range func to create list
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [233]:
# similarly we have arange function , arange stands for array range 
arr = np.arange(1,11,dtype=int)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [234]:
# similarly we can define the step size
arr1 = np.arange(1,20,2,dtype=int)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [235]:
# array of random numbers
# 1 se 10 ke beech 5 nos
arr = np.random.randint(1,10,5,dtype=int)
print(arr)

[6 4 5 4 2]


In [236]:
#  here it gave 5 random numbers lower bound 1 & upper bound is 10 and total values to be returned are 5

In [237]:
# 2d array with value between 0 to 1
arr = np.random.random((5,3))
print(arr)

[[0.57559219 0.60214338 0.02429876]
 [0.50978214 0.62090606 0.10406688]
 [0.5815755  0.29223389 0.65776767]
 [0.78024059 0.46848852 0.5898213 ]
 [0.59590167 0.15242443 0.70056236]]


In [238]:
arr = np.linspace(1,10,20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [239]:
# create an array of any number

arr = np.full((2,3),fill_value = 2.0)
print(arr)

[[2. 2. 2.]
 [2. 2. 2.]]


In [240]:
# identitiy element
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Stacking arrays

we have the functions np.hstack() and np.vstack() , hstack stands for horizontal stacking for this the nos of rows must be same, vstack stands for the vertical stacking for this the columns must be same.

In [241]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

print("Horizontal Stacking : ",np.hstack((arr1,arr2)))

Horizontal Stacking :  [1 2 3 4 5 2 3 4 5 6]


In [242]:
print("Vertical Stacking :  ",np.vstack((arr1,arr2)))

Vertical Stacking :   [[1 2 3 4 5]
 [2 3 4 5 6]]


## Broadcasting in Numpy

Broadcasting is a powerful feature in NumPy that allows arithmetic operations between arrays of different shapes. Instead of raising an error when shapes mismatch, NumPy tries to adjust the shapes (without copying data) to make the operation possible.

NumPy compares the shapes of two arrays element-wise, starting from the rightmost dimension.<br/>
If the dimensions match or one of them is 1, broadcasting is possible.

In [245]:
#Shape of a: (3,)
#Shape of b: () → Broadcasted to (3,)
a = np.array([1, 2, 3])
b = 2
result = a * b
print(result)  

[2 4 6]


In [246]:
# 2d array with 1 d array
#Shape of a: (2, 3)
#Shape of b: (3,) → Broadcasted to (2, 3)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


In [247]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a.shape)
print(b.shape)
result = a + b
print(result)

(3, 1)
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]
